[package]
name = "tdgame"
version = "0.1.0"
authors = ["gen"]
edition = "2018"

[dependencies]
# Misc
derive_more = "0.99"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"

#features = ["dynamic"]